coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 2%

flag_management:
  default_rules:
    carryforward: true

flags:
  frontend:
    paths:
      - src/lib/
    carryforward: true
  rust:
    paths:
      - src-tauri/src/
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
